### ISSUE TITLE
[Carbon][Download PNG] Request failed with status code 503

### ISSUE THREAD

**Issue by jingkecn** [whosydd/carbon#1]
Carbon: Download PNG
> Request failed with status code 503

**Comment by whosydd** [comment]
由于默认使用的是 [petersolopov/carbonara](https://github.com/petersolopov/carbonara) 提供的 api 端口，应该是接口出现问题，我会尝试重新部署一个新的 api 接口，很抱歉暂时无法帮助到你。

**Comment by jingkecn** [comment]
沒關係，這是個很實用的插件，加油💪

**Comment by nezaboravi** [comment]
Hello, i am having the same issue on MacBook, Ventura

**Comment by whosydd** [comment]
@nezaboravi 

Hi, the current api is not available. I'm trying to figure out how to fix this.

**Comment by whosydd** [comment]
@nezaboravi @jingkecn 
I deployed [new api](https://github.com/whosydd/carbon-api) and updated the extension, have fun！

**Comment by nezaboravi** [comment]
> @nezaboravi @jingkecn I deployed [new api](https://github.com/whosydd/carbon-api) and updated the extension, have fun！

thanks buddy, works nice!
![SearchTasks vue-2022-12-24-14-20-30](https://user-images.githubusercontent.com/1515172/209425779-022e7c28-bdc1-4788-8d20-560a2b11d1a0.png)

**Comment by whosydd** [comment]
@jingkecn 
这个 issue 我就关闭了，如果还有问题，请提交新的 issue
